#checkov:skip=CKV_GHA_7
name: Update major tag for release
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name that the major tag will point to (e.g. v1.2.3)"
        required: true
env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
permissions:
  contents: read
jobs:
  update_tag:
    permissions:
      contents: write
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@8a4b4f687b72f481b8a241ef71f38857239698fc
        with:
          source-tag: ${{ env.TAG_NAME }}
